# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: true
check_commit_message: false
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: false
deploy_client_to_rubygems: false
deploy_daily_client_to_pypi: false
deploy_daily_client_to_rubygems: false
deploy_to_pypi: false
docker_fixtures: false
docs_test: false
plugin_app_label: cookbook
plugin_camel: PulpCookbook
plugin_camel_short: Cookbook
plugin_caps: PULP_COOKBOOK
plugin_caps_short: COOKBOOK
plugin_dash: pulp-cookbook
plugin_dash_short: cookbook
plugin_name: pulp_cookbook
plugin_snake: pulp_cookbook
pulp_settings: null
pulpcore_branch: master
pydocstyle: true
pypi_username: null
stable_branch: null
test_bindings: false
test_performance: false
travis_notifications: null

